#!/usr/bin/env python
# coding: utf-8

# ### # 1. Import Libraries & Load Data 

# In[1]:


get_ipython().system('pip install prophet')


# In[2]:


import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from prophet import Prophet


df = pd.read_csv("sales_dataset.csv", parse_dates=["Order Date"])


print(df.head())
print(df.info())


# ### # 2. Data Cleaning

# In[3]:


df["Order Date"] = pd.to_datetime(df["Order Date"], errors="coerce")


df = df.dropna(subset=["Order Date", "Total Sales"])


df = df.drop_duplicates()


print(df.describe())


# ### # 3. Exploratory Data Analysis (EDA)

# ###### 3.1Monthly sales Trend

# In[4]:


monthly_sales = df.groupby(df["Order Date"].dt.to_period("M")).sum(numeric_only=True)["Total Sales"]
monthly_sales.index = monthly_sales.index.to_timestamp()

plt.figure(figsize=(12,6))
plt.plot(monthly_sales.index, monthly_sales.values, marker='o')
plt.title("Monthly Sales Trend", fontsize=16)
plt.xlabel("Month")
plt.ylabel("Total Sales")
plt.grid(True)
plt.show()


# ###### 3.2 Sales by Category

# In[5]:


category_sales = df.groupby("Category")["Total Sales"].sum().sort_values(ascending=False)

plt.figure(figsize=(8,5))
sns.barplot(x=category_sales.values, y=category_sales.index)
plt.title("Total Sales by Category", fontsize=14)
plt.xlabel("Sales Amount")
plt.ylabel("Category")
plt.show()


# ###### 3.3 Top 10 Products

# In[6]:


top_products = df.groupby("Product")["Total Sales"].sum().sort_values(ascending=False).head(10)

plt.figure(figsize=(8,5))
sns.barplot(x=top_products.values, y=top_products.index)
plt.title("Top 10 Products by Sales", fontsize=14)
plt.xlabel("Sales Amount")
plt.ylabel("Product")
plt.show()


# ###### 3.4 Sales by Region

# In[7]:


region_sales = df.groupby("Region")["Total Sales"].sum().sort_values(ascending=False)

plt.figure(figsize=(8,5))
sns.barplot(x=region_sales.values, y=region_sales.index)
plt.title("Total Sales by Region", fontsize=14)
plt.xlabel("Sales Amount")
plt.ylabel("Region")
plt.show()


# ### 4. Sales Forecasting with Prophet

# In[8]:


import pandas as pd
import matplotlib.pyplot as plt
from prophet import Prophet


df = pd.read_csv("sales_dataset.csv")


df['Order Date'] = pd.to_datetime(df['Order Date'])


sales_col = "Total Sales"


monthly_sales = df.groupby(pd.Grouper(key='Order Date', freq='M'))[sales_col].sum().reset_index()


forecast_df = monthly_sales.rename(columns={"Order Date": "ds", sales_col: "y"})


model = Prophet()
model.fit(forecast_df)


future = model.make_future_dataframe(periods=6, freq='M')


forecast = model.predict(future)


fig1 = model.plot(forecast)
plt.title("Sales Forecast for Next 6 Months", fontsize=16)
plt.xlabel("Date")
plt.ylabel("Total Sales")
plt.show()


fig2 = model.plot_components(forecast)
plt.show()


print(forecast[['ds', 'yhat', 'yhat_lower', 'yhat_upper']].tail(6))


# In[ ]:




